AWSTemplateFormatVersion: "2010-09-09"
## =================== DESCRIPTION =================== ##
Description: >-
  AWS S3 who contains all CF Ctack
  - used in each topic
  - refered in the html page of each topic for reproduing every topic by CF quick-create link

## =================== RESOURCES =================== ##
Resources:
  myS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3-lyc-handson-cfstacks
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain
    
  myBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref myS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "${myS3Bucket.Arn}/*"

